INSERT INTO guests (full_name, normalized_name) VALUES
  ('Gledston', 'gledston'),
  ('Camila', 'camila'),
  ('Maria Eduarda', 'maria eduarda'),
  ('Nicolas', 'nicolas'),
  ('Elias', 'elias'),
  ('Sinair', 'sinair'),
  ('Ana', 'ana'),
  ('Renner', 'renner'),
  ('Elian', 'elian'),
  ('Pedro', 'pedro'),
  ('Julia', 'julia'),
  ('Elon', 'elon'),
  ('Eliete', 'eliete'),
  ('Junior', 'junior'),
  ('Cleide', 'cleide'),
  ('Samuel', 'samuel'),
  ('Ygor', 'ygor'),
  ('Stephany', 'stephany'),
  ('Edma', 'edma'),
  ('Romeu', 'romeu'),
  ('Eliene', 'eliene'),
  ('Juliana', 'juliana'),
  ('Geovanna', 'geovanna'),
  ('Elizabeth', 'elizabeth'),
  ('Tia Maria', 'tia maria'),
  ('Marcos', 'marcos'),
  ('Sandro', 'sandro'),
  ('Kelly', 'kelly'),
  ('Akemi', 'akemi'),
  ('Joaozinho', 'joaozinho'),
  ('Valdinair', 'valdinair'),
  ('Joao filho', 'joao filho'),
  ('Cleomar', 'cleomar'),
  ('Valdirene', 'valdirene'),
  ('Rubis', 'rubis'),
  ('Lena', 'lena'),
  ('Nercidio', 'nercidio'),
  ('Lucia', 'lucia'),
  ('Lieci', 'lieci'),
  ('Jose', 'jose'),
  ('Cida', 'cida'),
  ('Lindomar', 'lindomar'),
  ('Jerominho', 'jerominho'),
  ('Adelia', 'adelia'),
  ('Celia', 'celia'),
  ('Tereza', 'tereza'),
  ('Rogerio', 'rogerio'),
  ('Aracelle', 'aracelle'),
  ('Mauricio', 'mauricio'),
  ('Lorena', 'lorena'),
  ('Rose', 'rose'),
  ('Dilson', 'dilson'),
  ('Luciana', 'luciana'),
  ('Marcio', 'marcio'),
  ('Alice', 'alice'),
  ('Ricardo', 'ricardo'),
  ('Vanessa', 'vanessa'),
  ('Murilo', 'murilo'),
  ('Delio Junior', 'delio junior'),
  ('Cardec', 'cardec'),
  ('Aline', 'aline'),
  ('Delio', 'delio'),
  ('Roberto', 'roberto'),
  ('Leila', 'leila'),
  ('Rochael', 'rochael'),
  ('Claudith', 'claudith'),
  ('Marcio Rios', 'marcio rios'),
  ('Kelly Rios', 'kelly rios'),
  ('Silzimar', 'silzimar'),
  ('Heitor', 'heitor'),
  ('Suzi', 'suzi'),
  ('Raquel', 'raquel'),
  ('Duda', 'duda'),
  ('Joao Pedro', 'joao pedro'),
  ('Divina', 'divina'),
  ('Gilvan', 'gilvan'),
  ('Cristiane', 'cristiane'),
  ('Debora', 'debora'),
  ('Gilberto', 'gilberto'),
  ('Rafael', 'rafael'),
  ('Thamires', 'thamires'),
  ('Luana', 'luana'),
  ('Kalu', 'kalu'),
  ('Jose Junior', 'jose junior'),
  ('Tio Ze', 'tio ze'),
  ('Elizena', 'elizena'),
  ('Cezar Augusto', 'cezar augusto'),
  ('Rivone', 'rivone'),
  ('Wesley', 'wesley'),
  ('Joao Vitor', 'joao vitor'),
  ('Isabela', 'isabela'),
  ('Deija', 'deija'),
  ('Zezinho', 'zezinho'),
  ('Priscila', 'priscila'),
  ('Jessica', 'jessica'),
  ('Maycon', 'maycon'),
  ('Fernando', 'fernando'),
  ('Angela', 'angela'),
  ('Luana Veruska', 'luana veruska'),
  ('Jardel', 'jardel'),
  ('Filipe', 'filipe'),
  ('Roselito', 'roselito'),
  ('Eny', 'eny'),
  ('Tarcisio', 'tarcisio'),
  ('Junior Cesar', 'junior cesar'),
  ('Ester', 'ester'),
  ('Sonia', 'sonia'),
  ('Jakeline', 'jakeline'),
  ('Johnathan', 'johnathan'),
  ('Joana', 'joana'),
  ('Antonio Carlos', 'antonio carlos'),
  ('Nilson', 'nilson'),
  ('Flaviano', 'flaviano'),
  ('Suener', 'suener'),
  ('Waldivino', 'waldivino'),
  ('Inacio', 'inacio'),
  ('Sonia Alexandra', 'sonia alexandra'),
  ('Denilson', 'denilson'),
  ('Daniel', 'daniel'),
  ('Angra', 'angra');
